title: <p align="center"> Kapil Bajaj</p>
logo: /assets/img/logo.png

description:
  <p align="center">
   <a href="https://www.linkedin.com/in/kapil-bajaj-2999bba/">LinkedIn</a> |
  <a href="https://github.com/kapilbajaj1911">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.

  <br>
  </p>



theme: jekyll-theme-minimal
